### ISSUE TITLE
Download the CytofBatchAdjust.R ?

### ISSUE THREAD

**Issue by OlivMC** [CUHIMSR/CytofBatchAdjust#2]
Hello ^^
I must admit I'm a noob with Github, but still I'll try to batch adjust my CyTOF data.
In the read me, it is written : "In an R session, navigate to where you downloaded BatchAdjust.R, and load the application..."
But how do you download the "CytofBatchAdjust.R" ?

Thanks a lot and in advance !!!

Olivier

**Comment by CUHIMSR** [comment]
Hi Olivier. There are many guides and tutorials online that will help you get started with github and R.
