### ISSUE TITLE
Run on Windows

### ISSUE THREAD

**Issue by sanhe374** [CUHIMSR/CytofBatchAdjust#4]
Hi!

I would like to do batch correction using anchor samples run during each batch, Is there anyway to run BatchAdjust in Windows?

**Comment by RonSchuyler** [comment]
Yes! Changes have been submitted but not yet reviewed and fully tested. I
expect this will be released by Thursday.

**Comment by sanhe374** [comment]
Thank you!

**Comment by SamGG** [comment]
Hi,
@sanhe374 you can find the pre-version at https://github.com/i-cyto/CytofBatchAdjust. Read also our HowTo, hoping it could help you to make it run. Also note an analysis I carried out with a colleague when comparing to cytoNorm. The HTML report could help you https://i-cyto.github.io/posts/200427-quantile_norm/.
@RonSchuyler thanks for reviewing, hope you are fine.
Best.

**Comment by tomashhurst** [comment]
@SamGG tried out your build in i-cyto, works well on windows -- currently using that code in [Spectre](https://github.com/ImmuneDynamics/Spectre).

**Comment by SamGG** [comment]
@tomashhurst Thanks for your feedback. I didn't try Spectre, but I am still keeping an eye on.
