### ISSUE TITLE
Error in processing a public dataset

### ISSUE THREAD

**Issue by masato-ogishi** [CUHIMSR/CytofBatchAdjust#5]
Hi,

I recently tried to batch-correct the data from the CytofRUV paper on MacOS, and encountered an error. Either using the first healthy control or the second, third ones as anchors. it looks like something went wrong in the getScalingFactors function.
http://flowrepository.org/id/RvFrVB2mAm2q08TjrWBEaJ4scGfMTPDwZiToOS22zcMztKarmVH563xYyFW78ZAL

Here's the channel file.
[ChannelsToAdjust.txt](https://github.com/CUHIMSR/CytofBatchAdjust/files/5239828/ChannelsToAdjust.txt)

Could you please take a look? Thanks!

Masato

**Comment by SamGG** [comment]
Hi,
Although it would be interesting to do a comparison, you are at the wrong place. Here it's CytofBatchAdjust.
You are looking at https://github.com/mtrussart/CytofRUV
Best.

**Comment by CUHIMSR** [comment]
I think Masato is trying to use BatchAdjust with data from the CytofRUV paper, which I think they described in that paper for comparison, so this would be the right place.

Masato, can you provide more details on the error you're seeing? Why do you suspect the getScalingFactors function?

**Comment by SamGG** [comment]
My bad. Sorry.
A copy/paste of the commands and the output would clearly show the error and help solving the problem quickly.

**Comment by masato-ogishi** [comment]
Maybe I was wrongly typing one of the channel names. The BatchAdjust script worked after fixing that name. I should have been more attentive. Sorry for bothering you!

**Comment by SamGG** [comment]
Don't hesitate to reopen if you get an error.
Your feedback would be interesting, here or on cytoforum.
Best.
