### ISSUE TITLE
no non-missing arguments to max returning -Infno non-missing arguments to min

### ISSUE THREAD

**Issue by ncborcherding** [CUHIMSR/CytofBatchAdjust#8]
Hey Sam,

I kept getting the erroe below when I called BatchAdjust with in percentile based adjustment

**My Code**
```
BatchAdjust(
   basedir="./eWAT",
   outdir="./eWAT/batch",
   channelsFile = "file.txt",
   batchKeyword="set_",
   anchorKeyword = "anchor",
   method="95p",
   transformation=FALSE,
   addExt=NULL,
   plotDiagnostics=FALSE)
```
**The Error**
<img width="619" alt="Screen Shot 2021-02-23 at 7 56 47 AM" src="https://user-images.githubusercontent.com/22754118/108853735-b1a2e700-75ac-11eb-91a0-e8e7efb22552.png">

After going over the BatchAdjust.R file, I found my channels were being labeled incorrectly, with the "/t/t/t" added, which is probably because I saved the file in excel as a tab-delimited .txt file
<img width="495" alt="Screen Shot 2021-02-23 at 7 48 46 AM" src="https://user-images.githubusercontent.com/22754118/108853879-d72ff080-75ac-11eb-8dc2-252933f1ca19.png">

In case anyone else is having this issue, the fix is to replace 

```
 cols_to_norm <- unique(as.character(read.table(file=channelsFile, header=F, sep='/n', quote="", as.is=TRUE)[,1]));
```

with the following to generate a table with NA values, and then select just the first column.
```
 cols_to_norm <- unique(as.character(read.delim(file=channelsFile, header=F, quote="", as.is=TRUE)[,1]));
```

Not sure if this is a common issue, but had me stumped for a couple of days. I do not think this necessarily needs to be changed . But wanted you to be aware of the potential problem.

Thanks,
Nick

**Comment by SamGG** [comment]
Hi,
Thanks for your feedback to the community.
It is a good practice to check file saved from Excel. I usually open saved files (either CSV or TXT or TSV) with a text editor and make it show the hidden characters such as the tabulation character \t. In Windows OS, I am a big fan of NotePad++.
Best.
